### ISSUE TITLE
Importo.py error:  unsupported format character 'S' (0x53) at index 30

### ISSUE THREAD

**Issue by HadeanDragon** [jmichault/gramps-kromprogramoj#29]
User Information: 
===================
I was able to use PersonFS for a good while (thanks!), but eventually the plugin is crashing when trying to import.  The plugin seems to pull the information correctly (I can view the person's information on the side bar), but crashes when I click 1-Click Import or Import.   I tried re-installing everything from scratch (except the database), so I have to assume there's something in the database itself?   There are no errors when I do the checks from within Gramps
Thanks!

Error Details: 
===================

64329: WARNING: connectionpool.py: line 331: Connection pool is full, discarding connection: api.familysearch.org. Connection pool size: 10
64505: WARNING: connectionpool.py: line 331: Connection pool is full, discarding connection: api.familysearch.org. Connection pool size: 10
93692: ERROR: grampsapp.py: line 188: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gramps/gui/plug/_windows.py", line 1820, in on_ok_clicked
    self.run()  # activate results tab
    ^^^^^^^^^^
  File "/home/hadean/.gramps/gramps52/plugins/PersonFS/Importo.py", line 1230, in run
    importilo.importi(self,self.FS_ID)
  File "/home/hadean/.gramps/gramps52/plugins/PersonFS/Importo.py", line 831, in importi
    print(_('«FamilySearch» duplikata ID : %s ')%(fsid))
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^~~~~~
ValueError: unsupported format character 'S' (0x53) at index 30


System Information: 
===================

Gramps version: 5.2.3 
Python version: 3.12.3 
BSDDB version: 6.2.9 (5, 3, 28) 
sqlite version: 3.45.1 (2.6.0) 
LANG: en_US.UTF-8
OS: Linux
Distribution: 6.8.0-38-generic

GTK version    : 3.24.41
gobject version: 3.48.2
cairo version  : (1, 25, 1)

**Comment by jmichault** [comment]
I pushed a new version that fixes this bug.
Thanks for trying it.

**Comment by HadeanDragon** [comment]
Both import buttons work perfectly!

Merci d'avoir répondu si rapidement !

**Comment by HadeanDragon** [comment]
Sorry, I spoke too soon.  It worked for a little while, but now I'm getting a very similar but slightly different error:


20102: ERROR: grampsapp.py: line 188: Unhandled exception
Traceback (most recent call last):
  File "/home/hadean/.gramps/gramps52/plugins/PersonFS/PersonFS.py", line 1489, in ButImp1K_clicked
    importilo.importi(self, fsid)
  File "/home/hadean/.gramps/gramps52/plugins/PersonFS/Importo.py", line 831, in importi
    print(_('«FamilySearch» duplikata ID : %s ')%(fsid))
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^~~~~~
ValueError: unsupported format character 'S' (0x53) at index 30

**Comment by jmichault** [comment]
Can't reproduce the bug.
Are you using the last release  (beta 2.0.45), and english language ?

**Comment by HadeanDragon** [comment]
Running the latest version (beta 2.0.45) and in English, yes.  I'm still getting the error with both kinds of Import, unfortunately.
